In [51]:
#Install Packages
!pip install faiss-cpu
!pip install sentence-transformers

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [53]:
# import necessary libraries
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [59]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [61]:
df

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel


In [63]:
!pip install sentence_transformers 

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [65]:
!pip uninstall -y keras

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Found existing installation: keras 3.10.0
Uninstalling keras-3.10.0:
  Successfully uninstalled keras-3.10.0


In [67]:
!pip install tf-keras

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


  Using cached keras-3.10.0-py3-none-any.whl.metadata (6.0 kB)
Using cached keras-3.10.0-py3-none-any.whl (1.4 MB)


In [71]:
from sentence_transformers import SentenceTransformer

In [73]:
encoder = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")
vectors = encoder.encode(df.text)

In [74]:
vectors.shape

(8, 768)

In [77]:
vectors

array([[-0.00247386,  0.03626726, -0.05290461, ..., -0.0915236 ,
        -0.03970009, -0.04330486],
       [-0.03357261,  0.00980522, -0.03250133, ..., -0.05165472,
         0.02245888, -0.03156187],
       [-0.01865335, -0.04051298, -0.01235388, ...,  0.00610581,
        -0.07179651,  0.02773849],
       ...,
       [-0.00066459,  0.04252124, -0.05645506, ...,  0.01315469,
        -0.03183556, -0.04357659],
       [-0.03317151,  0.03252463, -0.02484837, ...,  0.01174422,
         0.05747118,  0.00571025],
       [-0.00166393,  0.00413834, -0.04597077, ...,  0.02008527,
         0.05656247, -0.00161594]], dtype=float32)

In [79]:
vectors[1]

array([-3.35726142e-02,  9.80522204e-03, -3.25013250e-02,  1.86820347e-02,
        1.77040845e-02, -3.62626687e-02, -3.62390615e-02,  7.10840523e-02,
        2.47629602e-02,  2.63498500e-02, -1.21423870e-03, -1.13375084e-02,
       -1.15268948e-02,  1.43791353e-02, -4.38231118e-02, -2.79518887e-02,
        1.75678506e-02, -4.70075803e-03,  8.76717195e-02,  4.92547522e-04,
       -4.46607731e-02, -3.32105793e-02, -1.42118596e-02,  2.29376610e-02,
       -8.52664094e-03, -2.48494046e-03,  8.57962761e-03,  2.66635008e-02,
        2.85465922e-02, -2.94708051e-02, -4.25881967e-02,  1.92414615e-02,
       -2.21508536e-02, -5.22683226e-02,  9.17420437e-07, -2.53167879e-02,
       -5.45516610e-02,  6.14560694e-02, -1.15586063e-02,  1.64797045e-02,
        6.11990516e-04, -6.41633943e-02, -2.64592208e-02,  2.86634751e-02,
       -7.40521681e-03, -3.89426239e-02, -8.28322081e-04,  1.00291826e-01,
       -6.97325310e-03,  2.48220470e-02,  1.85312554e-02, -5.47105912e-03,
        2.40095090e-02, -

In [81]:
vectors.shape[1]

768

In [83]:
dim = vectors.shape[1]
dim

768

In [89]:
import faiss

index = faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x3469bedc0> >

In [91]:
index.add(vectors)

In [93]:
search_query = "I want to buy a polo t-shirt"
vec = encoder.encode(search_query)
vec.shape

(768,)

In [95]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [99]:
distances, I = index.search(svec, k=2)

In [101]:
I

array([[3, 2]])

In [103]:
df.loc[I[0]]

,text,category
3,Vibrant color jeans for male are becoming a trend,Fashion
2,These are the latest fashion trends for this week,Fashion


In [105]:
search_query

'I want to buy a polo t-shirt'

In [107]:
df

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel


In [97]:
index.search(svec,k=2)

(array([[1.3844836, 1.4039094]], dtype=float32), array([[3, 2]]))

In [35]:
faiss.normalize_L2(svec)

In [39]:
distances, I = index.search(svec, k=2)
distances

array([[1.3844839, 1.4039096]], dtype=float32)

In [41]:
I

array([[3, 2]])

In [43]:
I.tolist()

[[3, 2]]

In [45]:
row_indices = I.tolist()[0]
row_indices

[3, 2]

In [47]:
df.loc[row_indices]

,text,category
3,Vibrant color jeans for male are becoming a trend,Fashion
2,These are the latest fashion trends for this week,Fashion


In [49]:
search_query

'I want to buy a polo t-shirt'